config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :restaurants
  resources :dishes

  get "/signup", to: 'users#new', as: 'signup'
  get "/login",     to: 'sessions#new',     as: 'login'
  post "/sessions", to: "sessions#create",  as: 'sessions'
  post "/logout",   to: "sessions#destroy", as: 'logout'
  get '/users/:id/save_dish', to: "users#save_dish", as: 'save_dish'
  get '/users/:id/save_restaurant', to: "users#save_restaurant", as: 'save_restaurant'
  get "/mytakeaways", to: 'static#mytakeaways', as: 'mytakeaways'
    get "/dishes_regional", to: 'dishes#regional', as: 'regional'
  patch "/dish_rating/:id", to: "dishes#add_rating", as: "dishes_rating"
  patch "/restaurant_rating/:id", to: "restaurants#add_rating", as: "restaurants_rating"
  get "/analytics", to: 'analytics#index', as: 'analytics'
  root :to => 'static#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/dish.rb
class Dish < ApplicationRecord
  has_and_belongs_to_many :restaurants
  has_many :dishes_ratings
  has_many :users, through: :dishes_ratings


  def self.top_three
    DishesRating.all.order("rating desc").limit(3).map {|rating| rating.dish}
  end

  def saves
    DishesRating.all.select{ |dish| dish.dish_id == self.id}.count
  end

  def average_rating
    ratings = DishesRating.all.select{ |dish_rating| dish_rating.dish_id == self.id}.map {|rating| rating.rating}.compact
    if ratings.count > 0
      ratings.inject(:+)/ratings.count
    else
      return 0
    end
  end

  def get_coordinates_of_region
    chinese_region = self.region
    result = Geocoder.search(chinese_region)
    result.first.coordinates
  end

  def save_dish
  end
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController

  def index
    @dishes = Dish.all
  end

  def show
    @dish = Dish.find(params[:id])
    @query = @dish.name
    @rating = DishesRating.find_by(user_id: current_user.id, dish_id: @dish.id)
    @restaurants_with_dish = Restaurant.all.select {|restaurant| restaurant.dishes.include?(@dish)}
  end

  def new
    @dish = Dish.new
  end

  def create
    @dish = Dish.create(dish_params(:name, :description, :region, :rating, :image_url, :photo_1, :photo_2, :photo_3))
    redirect_to dish_path(@dish)
  end

  def add_rating
    rating = DishesRating.find(params[:id])
    rating.update(rating: params["score"])
    redirect_to dish_path(rating.dish)
  end

  def regional
    @dishes = Dish.all
  end

  def edit
    @dish = Dish.find(params[:id])
  end

  def update
    @dish = Dish.find(params[:id])
    @dish.update(dish_params)
    redirect_to dish_path(@dish)
  end

  def destroy
    Dish.find(params[:id]).destroy
    redirect_to dishes_path
  end

  private

  def dish_params
    params.require(:dish).permit(:name, :description, :region, :photo_1, :photo_2, :photo_3, restaurant_ids: [])
  end

end

# create_table "dishes", force: :cascade do |t|
#   t.string "name"
#   t.string "description"
#   t.string "region"
#   t.integer "rating"
#   t.string "photo_1"
#   t.string "photo_2"
#   t.string "photo_3"
#   t.datetime "created_at", null: false
#   t.datetime "updated_at", null: false
# end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/views/dishes/_form.html.erb
<div class="container">
  <%= form_for @dish do |f| %>
  <div class="form-group">
    <label for="name">Name</label>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <label for="region">Region</label>
    <%= f.text_field :region, class: "form-control" %>
  </div>
  <div class="form-group">
    <label for="region">Description</label>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <label for="photo_1">Photo 1</label>
    <%= f.text_field :photo_1, class: "form-control" %>
  </div>
  <div class="form-group">
    <label for="photo_2">Photo 2</label>
    <%= f.text_field :photo_2, class: "form-control" %>
  </div>
  <div class="form-group">
    <label for="photo_3">Photo 3</label>
    <%= f.text_field :photo_3, class: "form-control" %>
  </div>
  <div class="form-group">
    <label for="photo_3">Restaurants</label><br>
    <%= f.collection_check_boxes(:restaurant_ids, Restaurant.all, :id, :name)%>
  </div>
  <br>
  <%= f.submit :class => "btn btn-primary" %>
  <% end %>
</div>

<!-- Building number (:number)needs validation as integer -->
<!-- Postcode and name need to exist and name needs to be unique for postcode and number -->
<!-- Have cuisine attribute, alongside region to show unique dishes for different cuisines?-->

app/views/dishes/edit.html.erb
<div class="container new-form">
<% if @dish.errors.any? %>
  <div id="error_explanation">
    <p>There were some errors:</p>
    <ul>
      <% @dish.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <h1> Edit Dish </h1>
<%= render 'form' %>
</div>

app/views/dishes/index.html.erb
<div class="container">
  <div class="row dish-restaurant-index-nav">
  	<% if logged_in? && current_user.admin? %>
  		<div class="icon-container">
  			<a href=<%= new_dish_path(@dish) %>>
  			<h1><span class="fas fa-plus-circle"></h1>
  			<span class="my-text">Create New Dish</span>
  			</a>
  		</div>
  		<% end %>
  </div>
  <div class="container-fluid horizontal-scroll">
    <div class="row index-dishes-restaurant-titles">
      <h1> All Dishes </h1>
    </div>
    <div class="row flex-row flex-nowrap">
      <% @dishes.each do |dish| %>
        <div class="col-12 col-sm-12 col-md-6 col-lg-4">
          <div class="card card-block">
            <%= image_tag dish.photo_1, :class => "card-img" %>
          <h4><%= link_to dish.name, dish_path(dish), class: "dish-link" %></h4>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/dishes/new.html.erb
<div class="container new-form">
<% if @dish.errors.any? %>
  <div id="error_explanation">
    <p>There were some errors:</p>
    <ul>
      <% @dish.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <h1>New Dish</h1>
<%= render 'form' %>
</div>

app/views/dishes/regional.html.erb
<div class="container">
  <div class="row dish-restaurant-index-nav">
  </div>
    <div class="row index-dishes-restaurant-titles">
      <h1> All Dishes </h1>
    </div>
    <div class="row index-dishes-restaurant-titles">
      <h5>Click below to check out our collections of Chinese dishes by region.</h5>
    </div>
    <div class="row">
      <div class="regional-map-shell">
              <div id="regional-map-container" ></div>
            </div>
            <script type="text/javascript">
                var locations = <%= raw @dishes.map {|dish| [dish.name, dish.get_coordinates_of_region[0], dish.get_coordinates_of_region[1], dish.id, dish.region]} %>;
                console.log(locations);
                function initMap() {


                    var map = new google.maps.Map(document.getElementById('regional-map-container'), {
                        zoom: 5,
                        center: new google.maps.LatLng(26.843, 107.2903),
                        mapTypeId: google.maps.MapTypeId.ROADMAP
                    });

                    var infowindow = new google.maps.InfoWindow();

                    var marker, i;

                    for (i = 0; i < locations.length; i++) {
                        marker = new google.maps.Marker({
                            position: new google.maps.LatLng(locations[i][1], locations[i][2]),
                            map: map
                        });

                        google.maps.event.addListener(marker, 'click', (function (marker, i) {
                            return function () {
                              var contentString = '<div id="content">'+
                              '<div id="siteNotice">'+
                              '</div>'+
                              `<h5 id="firstHeading" class="firstHeading"><a href="/dishes/${locations[i][3]}">
                              ${locations[i][0]}</a></h5>`+
                              `<div id="bodyContent"><p>${locations[i][4]}</p>
                              </div>`+
                              '</div>';
                                infowindow.setContent(contentString);
                                infowindow.open(map, marker);
                            }
                        })(marker, i));
                    }
                }
            </script>
            <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAWHIVYglIX-UITv9CS6aXjTkrfL7Zm200&callback=initMap">
            </script>

      </div>
    </div>

app/views/dishes/show.html.erb
<div class="row dish-restaurant-nav">
	<div class="icon-container">
		<a href=<%= dishes_path %>>
		<h1><span class="fas fa-arrow-circle-left"></h1>
			<span class="my-text">Back to all Dishes</span>
		</a>
	</div>
	<% if logged_in? && current_user.admin? %>
		<div class="icon-container">
			<a href=<%= edit_dish_path(@dish) %>>
			<h1><span class="far fa-edit"></h1>
			<span class="my-text">Edit Dish</span>
			</a>
		</div>
		<div class="icon-container">
			<a href="/dishes/<%=@dish.id%>" data-method="delete">
			<h1><span class="far fa-trash-alt"></h1>
			<span class="my-text">Delete Dish</span>
			</a>
		</div>
		<% end %>
	<% if logged_in? %>
		<% if current_user.dishes.include?(@dish) %>
		<div class="icon-container">
			<a href=<%= save_dish_path %>>
			<h1><span class="fas fa-star"></h1>
			<span class="my-text">Unsave dish?</span>
			</a>
		</div>
		<% else %>
		<div class="icon-container">
			<a href=<%= save_dish_path %>>
			<h1><span class="far fa-star"></h1>
			<span class="my-text">Save this dish</span>
			</a>
		</div>
		<% end %>
	<% end %>
</div>
<div class="container">
	<div class="row title">
		<h1><%= @dish.name %></h1>
	</div>
	<div class="row">
		<div	class="col-md-6">
		<img class="image" id="imgClickAndChange" alt="" src="<%= @dish.photo_1 %>" onclick="changeImage()" >
		</div>
		<div class="col-md-6">
			<div class="row rating-row">
				<% if current_user.dishes.include?(@dish) %>
			<div class="form-group">
				<%= form_for @rating do |f| %>
				<div id='star-rating'></div>
		</div>
		<%= f.submit "➜", class: "rating-send-button" %>
		<% end %>
<% end %>
		</div>
			<p>Main Region: <%= @dish.region %> </p>
			<%= @dish.description %>
			<br />
			<br />
			<h5>Average Rating: <%= @dish.average_rating %> / 5</h5>
			<h5>Saved <%= @dish.saves %> times</h5>
		</div>
	</div><p>
		<div class="row">
			<h2 class="restaurants-list-header">Restaurants with this dish</h2>
		</div>
			<div class="row">
				<ol>
					<% @restaurants_with_dish.each do |restaurant| %>
						<h4><li><%= link_to restaurant.name, restaurant_path(restaurant) %> , <%= restaurant.postcode %> <% if logged_in? %> (<%=restaurant.proximity_to_user(current_user).round(2) %> km)<% end %></li></h4>
					<% end %>
				</ol>
			</div>
	</div>
</div>

<% if current_user.dishes.include?(@dish) %>
<script language="javascript">
	var num = 0;

	setInterval (function changeImage() {
		var images = ["<%= @dish.photo_1 %>", "<%= @dish.photo_2 %>", "<%= @dish.photo_3 %>"]
	    var len = images.length;
			let img = document.getElementById("imgClickAndChange")
	    img.src = images[num++];
	    if (num == len) {
	        num = 0;
		};
	}, 4000);

	$('div#star-rating').raty({
		path: '/assets/',
		score:
		function() {
			<% if !!@rating.rating && @rating.rating > 0 %>
				return <%= @rating.rating %>
			<% else %>
					return $(this).attr('data-score');
			<% end %>
		},
	});
</script>
<% end %>