config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :restaurants
  resources :dishes

  get "/signup", to: 'users#new', as: 'signup'
  get "/login",     to: 'sessions#new',     as: 'login'
  post "/sessions", to: "sessions#create",  as: 'sessions'
  post "/logout",   to: "sessions#destroy", as: 'logout'
  get '/users/:id/save_dish', to: "users#save_dish", as: 'save_dish'
  get '/users/:id/save_restaurant', to: "users#save_restaurant", as: 'save_restaurant'
  get "/mytakeaways", to: 'static#mytakeaways', as: 'mytakeaways'
    get "/dishes_regional", to: 'dishes#regional', as: 'regional'
  patch "/dish_rating/:id", to: "dishes#add_rating", as: "dishes_rating"
  patch "/restaurant_rating/:id", to: "restaurants#add_rating", as: "restaurants_rating"
  get "/analytics", to: 'analytics#index', as: 'analytics'
  root :to => 'static#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_and_belongs_to_many :dishes
  has_many :restaurants_ratings
  has_many :users, through: :restaurants_ratings


    def get_address
      if self.address != nil
      "#{self.address + " " + self.postcode}"
      else
      self.postcode
      end
    end

    def self.top_three
      RestaurantsRating.all.order("rating desc").limit(3).map {|rating| rating.restaurant}
    end

    def get_coordinates
        url = "https://api.postcodes.io/postcodes/" + self.postcode.gsub(/\s+/, "").downcase
        response = HTTParty.get(url).parsed_response
        result = []
        result << response["result"]["latitude"]
        result << response["result"]["longitude"]
        result
    end

    def saves
      RestaurantsRating.all.select{ |restaurant| restaurant.restaurant_id == self.id}.count
    end

    def average_rating
      ratings = RestaurantsRating.all.select{ |restaurant_rating| restaurant_rating.restaurant_id == self.id}.map {|rating| rating.rating}.compact
      if ratings.count > 0
        ratings.inject(:+)/ratings.count
      else
        return 0
      end
    end

    def check_number
      self.number.to_f
    end

    def proximity_to_user(current_user)
      url = "https://api.postcodes.io/postcodes/" + self.postcode.gsub(/\s+/, "").downcase
      response = HTTParty.get(url).parsed_response
      restaurant_coordinates = []
      restaurant_coordinates << response["result"]["latitude"]
      restaurant_coordinates << response["result"]["longitude"]
      user_coordinates = current_user.get_coordinates
      distance = Geocoder::Calculations.distance_between(restaurant_coordinates, user_coordinates)
      distance
    end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all.select {|r| r.postcode.length > 4}
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @rating = RestaurantsRating.find_by(user_id: current_user.id, restaurant_id: @restaurant.id)
    @address = Geocoder.search(@restaurant.postcode)
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.create(restaurant_params)

    redirect_to restaurant_path(@restaurant)
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def add_rating
    rating = RestaurantsRating.find(params[:id])
    rating.update(rating: params["score"])
    redirect_to restaurant_path(rating.restaurant)
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    Restaurant.find(params[:id]).destroy
    redirect_to restaurants_path
  end

private

  def restaurant_params
    params.require(:restaurant).permit(:name, :number, :postcode, :phone_number, dish_ids: [])
  end
# To get a strong params to acccept an attribute array, you need to explicitly state it such as 'dish_ids: []'
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<div class="container">
  <%= form_for @restaurant do |f| %>
  <div class="form-group">
    <label for="name">Name</label>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <label for="address">Address</label>
    <%= f.text_field :address, class: "form-control" %>
  </div>
  <div class="form-group">
    <label for="postcode">Postcode</label>
    <%= f.text_field :postcode, class: "form-control" %>
  </div>
  <div class="form-group">
    <label for="dishes">Dishes</label>
    <br>
    <%= f.collection_check_boxes(:dish_ids, Dish.all, :id, :name)%>
  </div>
  <br>
  <%= f.submit :class => "btn btn-primary" %>
  <% end %>
</div>

<!-- Building number (:number)needs validation as integer -->
<!-- Postcode and name need to exist and name needs to be unique for postcode and number -->
<!-- Have cuisine attribute, alongside region to show unique dishes for different cuisines?-->

app/views/restaurants/edit.html.erb
<div class="container new-form">
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <p>There were some errors:</p>
      <ul>
        <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <h1> Edit Restaurant </h1>
  <%= render 'form' %>
<p>
</div>

app/views/restaurants/index.html.erb
<div class="container">
  <div class="row dish-restaurant-index-nav">
  	<% if logged_in? && current_user.admin? %>
  		<div class="icon-container">
  			<a href=<%= new_restaurant_path(@restaurant) %>>
  			<h1><span class="fas fa-plus-circle"></h1>
  			<span class="my-text">Create New Restaurant</span>
  			</a>
  		</div>
  		<% end %>
  </div>
    <div class="row index-dishes-restaurant-titles">
      <h1> All Takeaways </h1>
    </div>

    <div class="container all-restaurants-map-shell">
      <div id="all-restaurants-map-container" ></div>
    </div>
    <script type="text/javascript">
        var locations = <%= raw @restaurants.map {|restaurant| [restaurant.name, restaurant.get_coordinates[0], restaurant.get_coordinates[1], restaurant.id, restaurant.address]} %>;
        console.log(locations);
        function initMap() {


            var map = new google.maps.Map(document.getElementById('all-restaurants-map-container'), {
                zoom: 12,
                center: new google.maps.LatLng(51.5138, -0.15),
                mapTypeId: google.maps.MapTypeId.ROADMAP
            });

            var infowindow = new google.maps.InfoWindow();

            var marker, i;

            for (i = 0; i < locations.length; i++) {
                marker = new google.maps.Marker({
                    position: new google.maps.LatLng(locations[i][1], locations[i][2]),
                    map: map
                });

                google.maps.event.addListener(marker, 'click', (function (marker, i) {
                    return function () {
                      var contentString = '<div id="content">'+
                      '<div id="siteNotice">'+
                      '</div>'+
                      '<h5 id="firstHeading" class="firstHeading">'+locations[i][0]+'</h5>'+
                      '<div id="bodyContent">'+
                      `<p> <a href="/restaurants/${locations[i][3]}">
                      ${locations[i][4]}</a>`+
                      '</div>'+
                      '</div>';
                        infowindow.setContent(contentString);
                        infowindow.open(map, marker);
                    }
                })(marker, i));
            }
        }
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAWHIVYglIX-UITv9CS6aXjTkrfL7Zm200&callback=initMap">
    </script>

  </div>
</div>

app/views/restaurants/new.html.erb
<div class="container new-form">
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <p>There were some errors:</p>
      <ul>
        <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <h1> New Restaurant </h1>
  <%= render 'form' %>
</div>

app/views/restaurants/show.html.erb
<div class="row dish-restaurant-nav">
	<div class="icon-container">
		<a href=<%= restaurants_path %>>
		<h1><span class="fas fa-arrow-circle-left"></h1>
			<span class="my-text">Back to all Restaurants</span>
		</a>
	</div>
	<% if logged_in? && current_user.admin? %>
		<div class="icon-container">
			<a href=<%= edit_restaurant_path(@restaurant) %>>
			<h1><span class="far fa-edit"></h1>
			<span class="my-text">Edit Restaurant</span>
			</a>
		</div>
		<div class="icon-container">
			<a href="/dishes/<%=@restaurant.id%>" data-method="delete">
			<h1><span class="far fa-trash-alt"></h1>
			<span class="my-text">Delete Restaurant</span>
			</a>
		</div>
		<% end %>
	<% if logged_in? %>
		<% if current_user.restaurants.include?(@restaurant) %>
		<div class="icon-container">
			<a href=<%= save_restaurant_path %>>
			<h1><span class="fas fa-star"></h1>
			<span class="my-text">Unsave restaurant?</span>
			</a>
		</div>
		<% else %>
		<div class="icon-container">
			<a href=<%= save_restaurant_path %>>
			<h1><span class="far fa-star"></h1>
			<span class="my-text">Save this restaurant</span>
			</a>
		</div>
		<% end %>
	<% end %>
</div>
<div class="container">
	<div class="row title">
		<h1><%= @restaurant.name %></h1>
	</div>
	<div class="row">
		<div	class="col-md-6">
      <!--The div element for the map -->
      <div class="container" id="map-container">
      </div>
      <script>
          // Initialize and add the map
          function initMap() {
            // The location of Uluru
            var place = {lat: <%= @restaurant.get_coordinates[0] %> , lng: <%= @restaurant.get_coordinates[1] %>};
            // The map, centered at Uluru
            var map = new google.maps.Map(
                document.getElementById('map-container'), {zoom: 12, center: place});
            // The marker, positioned at Uluru
            var marker = new google.maps.Marker({position: place, map: map});
          }
      </script>
      <script async defer
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAWHIVYglIX-UITv9CS6aXjTkrfL7Zm200&callback=initMap">
      </script>
		</div>
		<div class="col-md-6">
			<div class="row rating-row">
				<% if current_user.restaurants.include?(@restaurant) %>
			<div class="form-group">
				<%= form_for @rating do |f| %>
				<div id='star-rating'></div>
		</div>
		<%= f.submit "➜", class: "rating-send-button" %>
		<% end %>
<% end %>
		</div>
		<h5>Contact</h5>
    <%= "#{@restaurant.address}" %><br>
		<%= "#{@restaurant.postcode}" %><br>
    <%= "#{@restaurant.phone_number}" %>
		<br />
		<br />
		<h5>Average Rating: <%= @restaurant.average_rating %> / 5</h5>
		<h5>Saved <%= @restaurant.saves %> times</h5>
		</div>
	</div><p>
		<div class="row">
			<h2 class="restaurants-list-header">Menu</h2>
		</div>
			<div class="row">
				<ol>
					<% @restaurant.dishes.each do |dish| %>
						<h4><li><%= link_to dish.name, dish_path(dish) %></li></h4>
					<% end %>
				</ol>
			</div>
	</div>
</div>

<% if current_user.restaurants.include?(@restaurant) %>
<script language="javascript">

	$('div#star-rating').raty({
		path: '/assets/',
		score:
		function() {
			<% if !!@rating.rating && @rating.rating > 0 %>
				return <%= @rating.rating %>
			<% else %>
					return $(this).attr('data-score');
			<% end %>
		},
	});
</script>
<% end %>