config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :restaurants
  resources :dishes

  get "/signup", to: 'users#new', as: 'signup'
  get "/login",     to: 'sessions#new',     as: 'login'
  post "/sessions", to: "sessions#create",  as: 'sessions'
  post "/logout",   to: "sessions#destroy", as: 'logout'
  get '/users/:id/save_dish', to: "users#save_dish", as: 'save_dish'
  get '/users/:id/save_restaurant', to: "users#save_restaurant", as: 'save_restaurant'
  get "/mytakeaways", to: 'static#mytakeaways', as: 'mytakeaways'
    get "/dishes_regional", to: 'dishes#regional', as: 'regional'
  patch "/dish_rating/:id", to: "dishes#add_rating", as: "dishes_rating"
  patch "/restaurant_rating/:id", to: "restaurants#add_rating", as: "restaurants_rating"
  get "/analytics", to: 'analytics#index', as: 'analytics'
  root :to => 'static#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TakeawayApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Baloo+Bhai|M+PLUS+Rounded+1c" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">


  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light navbar-custom">
  <a class="navbar-brand" href="<%= root_path %>">Bao Le Ma?! 飽了嗎 🍚🍜🌶: London's Chinese Takeaway Resource</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <% if admin? %>
        <li class="nav-item nav-link">
          <%= link_to "Analytics", analytics_path %>
        </li>
      <% end %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href='restaurants/index.html' id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Takeaways
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <%= link_to 'All Takeaways', restaurants_path, class: "dropdown-item" %>
          <%= link_to 'My Closest Takeaways', mytakeaways_path, class: "dropdown-item" %>
        </div>
      </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href='dishes/index.html' id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dishes
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <%= link_to 'All Dishes', dishes_path, class: "dropdown-item" %>
            <%= link_to 'Dishes by Regional Cuisine', regional_path, class: "dropdown-item" %>
          </div>
        </li>
        <% if logged_in? %>
        <li class="nav-item nav-link">
          <%= link_to "Log out", logout_path, method: "post" %> (<%= link_to current_user.username, user_path(current_user) %>)
        </li>
          <% else %>
          <%= link_to "Log in", login_path, class: "nav-item nav-link" %>
          <%= link_to "Sign up", signup_path, class: "nav-item nav-link" %>

          <% end %>
    </div>
  </div>
</nav>
    <% if flash[:authorized] %>
      <div class="alert alert-danger" role="alert">
        <%= flash[:authorized] %>
      </div>
    <% end %>

    <%= yield %>
  </body>
  <footer>COPYRIGHT © 2018.</footer>
</html>